name = "authentication-backend"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-28"
account_id = "5e933329e9723c7ff690bdb84a04b8d6"

kv_namespaces = [ 
    { binding = "AUTHENTICATION", preview_id = "1b309e13ef074d5eb7d0c7a9f3b9e8c0", id = "735816f20f0144b2b63384cc233cd2bf" }
]

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
